version: '3.9'
services:

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ecommerce-mongo:/data/db

  express:
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo

volumes:
  ecommerce-mongo:
    driver: local