version: '3.9'
services:

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ecommerce-mongo:/data/db

  express:
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_URI=${DB_URI}
      - VERIFICATION_SECRET_KEY=${VERIFICATION_SECRET_KEY}
      - ACCESS_TOKEN_SECRET_KEY=${ACCESS_TOKEN_SECRET_KEY}
      - REFRESH_TOKEN_SECRET_KEY=${REFRESH_TOKEN_SECRET_KEY}
      - RESET_PASSWORD_SECRET_KEY=${RESET_PASSWORD_SECRET_KEY}
      - SMPT_HOST=${SMPT_HOST}
      - SMPT_PORT=${SMPT_PORT}
      - SMPT_USER=${SMPT_USER}
      - SMPT_PASSWORD=${SMPT_PASSWORD}
      - SMPT_SECURE=${SMPT_SECURE}
    depends_on:
      - mongo

volumes:
  ecommerce-mongo:
    driver: local